### ISSUE TITLE
Rendering error with GAS made with multiple GeometryInstances in 02.scene_edit sample

### ISSUE THREAD

**Issue by Hurleyworks** [shocker-0x15/OptiX7_Utility#3]
This rendering error only occurs if the 6surf_box.OBJ is loaded after another object has been loaded into the scene. If you start with an empty scene and create an IAS for the 6surf_box.OBJ then it will render as expected.

Steps to reproduce:
1.  load 6surf_box.OBJ and create an IAS for it . Note that it renders correctly.
2.  close the application and start again
3.  load the subd_cube.OBJ and create an IAS for it and note that renders correctly.
4.  load 6surf_box.OBJ and create an IAS for it . Note the render errors ( all black )

[test_obj.zip](https://github.com/shocker-0x15/OptiX7_Utility/files/5012707/test_obj.zip)

**Comment by shocker-0x15** [comment]
Thanks for the report.
I stupidly forgot to use GAS::setUserData()!
Inside the kernel, it use HitGroupSBTRecordData::gasData as an index to identify per-GAS data, but I forgot to set the value from the host-side.

**Comment by Hurleyworks** [comment]
Works fine now.  Thanks for the quick fix
